include:
  - board: xiao_ble
    shield: adept_board rgbled_adapter
    # snippet: zmk-usb-logging
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: xiao_ble
    shield: settings_reset
